# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Project\YL1\design\EditFields_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditSupportForm(object):
    def setupUi(self, EditSupportForm):
        EditSupportForm.setObjectName("EditSupportForm")
        EditSupportForm.setWindowModality(QtCore.Qt.ApplicationModal)
        EditSupportForm.resize(550, 300)
        EditSupportForm.setMinimumSize(QtCore.QSize(550, 300))
        EditSupportForm.setMaximumSize(QtCore.QSize(550, 300))
        self.horizontalLayoutWidget = QtWidgets.QWidget(EditSupportForm)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 551, 301))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.main_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.main_layout.setContentsMargins(1, 1, 1, 1)
        self.main_layout.setSpacing(5)
        self.main_layout.setObjectName("main_layout")
        self.ops_layout = QtWidgets.QVBoxLayout()
        self.ops_layout.setObjectName("ops_layout")
        self.select_ops_rdbtn = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.select_ops_rdbtn.setMinimumSize(QtCore.QSize(0, 20))
        self.select_ops_rdbtn.setObjectName("select_ops_rdbtn")
        self.ops_layout.addWidget(self.select_ops_rdbtn)
        self.ops_table = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.ops_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ops_table.setColumnCount(1)
        self.ops_table.setObjectName("ops_table")
        self.ops_table.setRowCount(0)
        self.ops_table.horizontalHeader().setCascadingSectionResizes(True)
        self.ops_layout.addWidget(self.ops_table)
        self.ops_ctrl_grid = QtWidgets.QGridLayout()
        self.ops_ctrl_grid.setObjectName("ops_ctrl_grid")
        self.op_name_txt = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.op_name_txt.setObjectName("op_name_txt")
        self.ops_ctrl_grid.addWidget(self.op_name_txt, 0, 1, 1, 1)
        self.add_new_op_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.add_new_op_btn.setMinimumSize(QtCore.QSize(120, 0))
        self.add_new_op_btn.setObjectName("add_new_op_btn")
        self.ops_ctrl_grid.addWidget(self.add_new_op_btn, 0, 0, 1, 1)
        self.del_cur_op_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.del_cur_op_btn.setObjectName("del_cur_op_btn")
        self.ops_ctrl_grid.addWidget(self.del_cur_op_btn, 1, 1, 1, 1)
        self.ops_layout.addLayout(self.ops_ctrl_grid)
        self.main_layout.addLayout(self.ops_layout)
        self.cats_layout = QtWidgets.QVBoxLayout()
        self.cats_layout.setObjectName("cats_layout")
        self.select_cats_rdbtn = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.select_cats_rdbtn.setMinimumSize(QtCore.QSize(0, 20))
        self.select_cats_rdbtn.setObjectName("select_cats_rdbtn")
        self.cats_layout.addWidget(self.select_cats_rdbtn)
        self.cats_table = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.cats_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.cats_table.setColumnCount(1)
        self.cats_table.setObjectName("cats_table")
        self.cats_table.setRowCount(0)
        self.cats_layout.addWidget(self.cats_table)
        self.cats_ctrl_grid = QtWidgets.QGridLayout()
        self.cats_ctrl_grid.setObjectName("cats_ctrl_grid")
        self.add_new_cat_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.add_new_cat_btn.setMinimumSize(QtCore.QSize(120, 0))
        self.add_new_cat_btn.setObjectName("add_new_cat_btn")
        self.cats_ctrl_grid.addWidget(self.add_new_cat_btn, 0, 0, 1, 1)
        self.cat_name_txt = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.cat_name_txt.setObjectName("cat_name_txt")
        self.cats_ctrl_grid.addWidget(self.cat_name_txt, 0, 1, 1, 1)
        self.del_cur_cat_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.del_cur_cat_btn.setObjectName("del_cur_cat_btn")
        self.cats_ctrl_grid.addWidget(self.del_cur_cat_btn, 1, 1, 1, 1)
        self.cats_layout.addLayout(self.cats_ctrl_grid)
        self.main_layout.addLayout(self.cats_layout)

        self.retranslateUi(EditSupportForm)
        QtCore.QMetaObject.connectSlotsByName(EditSupportForm)

    def retranslateUi(self, EditSupportForm):
        _translate = QtCore.QCoreApplication.translate
        EditSupportForm.setWindowTitle(_translate("EditSupportForm", "Изменить служебные данные"))
        self.select_ops_rdbtn.setText(_translate("EditSupportForm", "Редактировать операции"))
        self.add_new_op_btn.setText(_translate("EditSupportForm", "Добавить"))
        self.del_cur_op_btn.setText(_translate("EditSupportForm", "Удалить"))
        self.select_cats_rdbtn.setText(_translate("EditSupportForm", "Редактировать категории"))
        self.add_new_cat_btn.setText(_translate("EditSupportForm", "Добавить"))
        self.del_cur_cat_btn.setText(_translate("EditSupportForm", "Удалить"))
